[build]
  # Netlify installs deps automatically; no need to run `npm install` again.
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Use a current LTS. If your project truly needs 18, keep it — otherwise prefer 20.
  NODE_VERSION = "20"

# ---------- API proxies (placed BEFORE SPA fallback) ----------
# Cloudflare Worker → API
[[redirects]]
  from = "/api/*"
  to = "https://seoscribe.frank-couchman.workers.dev/api/:splat"
  status = 200
  force = true

# Cloudflare Worker → Auth
[[redirects]]
  from = "/auth/*"
  to = "https://seoscribe.frank-couchman.workers.dev/auth/:splat"
  status = 200
  force = true

# ---------- SPA fallback ----------
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ---------- Security headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# ---------- Long-term cache for static assets ----------
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
